name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Install AWS CLI
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -o awscliv2.zip
          sudo ./aws/install --update

      # Step 4: Deploy to CodeDeploy
      - name: Deploy to CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name Todo-Backend \
            --deployment-group-name Todo-Backend-Group \
            --revision revisionType=GitHub \
              gitHubLocation='{"repository":"MayankTripathi033/Todo-backend"}' 
            --description "Deployment from GitHub Actions" \
            --query "deploymentId"
