name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 3: Install AWS CLI
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -o awscliv2.zip
          sudo ./aws/install --update

      # Step 4: Get the latest commit ID
      - name: Get latest commit ID
        id: get_commit
        run: echo "::set-output name=commit_id::$(git rev-parse HEAD)"

      # Step 5: Deploy to CodeDeploy
      - name: Deploy to CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name Todo-Backend \
            --deployment-group-name Todo-backend-Group \
            --revision '{"revisionType":"GitHub","gitHubLocation":{"repository":"MayankTripathi033/Todo-backend","commitId":"${{ steps.get_commit.outputs.commit_id }}"}}' \
            --description "Deployment from GitHub Actions" \
            --query "deploymentId"
