import mongoose from "mongoose";

const jobFeedSchema = new mongoose.Schema(
  {
    isAssigned: { type: Boolean, default: false },
    tlId: { type: String, default: "0" },
    amId: { type: String, default: "0" },
    finalUserAssignee: { type: String, default: "0" },
    durationType: { type: String },
    alias: { type: String },
    providerJobID: { type: Number, unique: true },
    customerID: { type: Number, default: 0 },
    sourceID: { type: String, unique: true },
    endDate: { type: String },
    sourceName: { type: String },
    postDate: { type: String },
    changeDate: { type: String },
    statusString: { type: String },
    startDate: { type: String },
    duration: { type: String },
    degree: { type: String },
    jobBoardDegree: { type: String, default: "" },
    jobBoardSpecialty: { type: String, default: "" },
    cleanDegree: { type: String, default: "NA" },
    cleanSpecialty: { type: String, default: "" },
    cleanShift: { type: String, default: "Unknown" },
    category: { type: String },
    facility: { type: String },
    unit: { type: String, default: "NA" },
    shift: { type: String },
    workType: { type: String },
    workLevel: { type: String, default: "" },
    billRate: { type: Number },
    guaranteedHours: { type: String, default: "" },
    bonus: { type: Number, default: 0 },
    local: { type: Boolean, default: false },
    address: { type: String, default: "" },
    city: { type: String },
    state: { type: String },
    zip: { type: String, default: "" },
    isASAP: { type: Boolean, default: false },
    hotFl: { type: Boolean, default: false },
    atsid: { type: String },
    mealStipendW: { type: Number, default: 0 },
    lodgingStipendW: { type: Number, default: 0 },
    totalStipendH: { type: Number, default: 0 },
    title: { type: String },
    chargeRate: { type: String, default: "" },
    callbackRate: { type: String, default: "0" },
    holidayRate: { type: String, default: "0" },
    buyer: { type: String, default: "" },
    coordinator: { type: String, default: "" },
    minBillRate: { type: Number },
    winterPlanNeed: { type: String, default: "No" },
    licenses: { type: String, default: "" },
    minExperienceRequired: { type: String, default: "" },
    industry: { type: String, default: "" },
    skills: { type: String, default: "" },
    jobURL: { type: String, default: "" },
    holdFl: { type: Boolean, default: false },
    bRate: { type: Number },
    externalVMSName: { type: String },
    formattedStartDate: { type: String },
    formattedEndDate: { type: String },
    customField1: { type: String, default: "" },
    customField2: { type: String, default: "" },
  },
  { timestamps: true }
);

const JobFeed = mongoose.model("jobRequistions", jobFeedSchema);

export default JobFeed;
